name: dduduk_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_core: ^31.2.12
  syncfusion_flutter_sliders: ^31.2.12
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 이미지, 아이콘 폴더 등록 (미리 해두면 편합니다)
  assets:
    - assets/images/
    - assets/icons/

  # 폰트 등록 
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
